<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMqs8NO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMqs8NO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMqs8NO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMqs8NO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAMqs8NO\App_KernelDevDebugContainer([
    'container.build_hash' => 'AMqs8NO',
    'container.build_id' => 'fc8ad9ea',
    'container.build_time' => 1679904999,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMqs8NO');
